services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: study_assistant_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
