'use server';

import { prisma } from '@/lib/prisma';
import { getCurrentUser } from '@/services/authService';
import { generateQuiz } from '@/services/gemini';
import { revalidatePath } from 'next/cache';

/**
 * Generate a quiz from a document using Gemini.
 */
export async function generateQuizAction(
  documentId: string,
  title: string,
  difficulty: string = 'medium',
  count: number = 5
) {
  const user = await getCurrentUser();
  if (!user) return { error: 'Unauthorized' };

  try {
    const doc = await prisma.document.findUnique({
      where: { id: documentId },
    });

    if (!doc || doc.userId !== user.id) {
      return { error: 'Document not found or unauthorized.' };
    }

    // Call Gemini API to generate quiz questions
    const questionData = await generateQuiz(doc.content, difficulty, count);

    // Save Quiz and Questions in database
    const quiz = await prisma.quiz.create({
      data: {
        userId: user.id,
        title: title || `Quiz on ${doc.name}`,
        difficulty,
        documentId: doc.id,
        totalQuestions: questionData.length,
        questions: {
          create: questionData.map(q => ({
            type: q.type,
            text: q.text,
            options: q.options,
            correctAnswer: q.correctAnswer,
            explanation: q.explanation,
          })),
        },
      },
      include: {
        questions: {
          select: {
            id: true,
            type: true,
            text: true,
            options: true,
            // Exclude correctAnswer and explanation initially to prevent cheating
          }
        }
      }
    });

    // Log Activity
    await prisma.activityLog.create({
      data: {
        userId: user.id,
        activity: 'Generated quiz',
        details: `Generated a ${difficulty} difficulty quiz with ${questionData.length} questions from "${doc.name}".`,
      },
    });

    revalidatePath('/dashboard');
    revalidatePath('/workspace');
    return { success: true, quiz };
  } catch (error) {
    console.error('Quiz generation error:', error);
    return { error: (error as Error).message };
  }
}

/**
 * Submit answers for a quiz. Checks answers, stores details, and returns full results.
 */
export async function submitQuizAnswersAction(quizId: string, submissions: { questionId: string; answer: string }[]) {
  const user = await getCurrentUser();
  if (!user) return { error: 'Unauthorized' };

  try {
    // Fetch original quiz questions with correct answers
    const quiz = await prisma.quiz.findUnique({
      where: { id: quizId },
      include: {
        questions: true,
      },
    });

    if (!quiz || quiz.userId !== user.id) {
      return { error: 'Quiz not found.' };
    }

    let correctCount = 0;
    const results = [];

    // Compare each submitted answer
    for (const question of quiz.questions) {
      const submission = submissions.find(s => s.questionId === question.id);
      const submittedAnswer = submission ? submission.answer.trim() : '';
      
      // Perform simple case-insensitive check
      const isCorrect = submittedAnswer.toLowerCase() === question.correctAnswer.trim().toLowerCase();
      
      if (isCorrect) {
        correctCount++;
      }

      // Save user answer to DB
      await prisma.userAnswer.create({
        data: {
          questionId: question.id,
          userId: user.id,
          answer: submittedAnswer,
          isCorrect,
        },
      });

      results.push({
        questionId: question.id,
        text: question.text,
        type: question.type,
        options: question.options,
        correctAnswer: question.correctAnswer,
        submittedAnswer,
        isCorrect,
        explanation: question.explanation,
      });
    }

    const finalScore = Math.round((correctCount / quiz.totalQuestions) * 100);

    // Save final score in database
    await prisma.quiz.update({
      where: { id: quizId },
      data: {
        score: finalScore,
      },
    });

    // Update User Stats
    await prisma.userStats.update({
      where: { userId: user.id },
      data: {
        quizzesCompleted: { increment: 1 },
      },
    });

    // Log Activity
    await prisma.activityLog.create({
      data: {
        userId: user.id,
        activity: 'Completed quiz',
        details: `Completed "${quiz.title}" with a score of ${finalScore}%.`,
      },
    });

    revalidatePath('/dashboard');
    revalidatePath('/workspace');
    return { success: true, score: finalScore, correctCount, totalQuestions: quiz.totalQuestions, results };
  } catch (error) {
    console.error('Quiz submission error:', error);
    return { error: (error as Error).message };
  }
}

/**
 * Fetch all quizzes completed/generated by the current user.
 */
export async function getQuizzesAction() {
  const user = await getCurrentUser();
  if (!user) return [];

  return prisma.quiz.findMany({
    where: { userId: user.id },
    orderBy: { createdAt: 'desc' },
  });
}

/**
 * Fetch a single quiz details (for taking it).
 */
export async function getQuizAction(quizId: string) {
  const user = await getCurrentUser();
  if (!user) return null;

  const quiz = await prisma.quiz.findUnique({
    where: { id: quizId },
    include: {
      questions: {
        select: {
          id: true,
          type: true,
          text: true,
          options: true,
          // Hide correctAnswer and explanation for active quiz taker
        }
      }
    }
  });

  if (!quiz || quiz.userId !== user.id) return null;
  return quiz;
}
